### ISSUE TITLE
Replace line feeds

### ISSUE THREAD

**Issue by predictiple** [Velocidex/evtx#10]
This makes the json a bit nicer for post-processing too:

`UPDATE
    messages
SET
    message = REPLACE(message, X'0A', '\n');`

**Comment by scudette** [comment]
Sorry I dont quite understand - can you give an example of a json output with undesirable characters? 

This might be a JSON escaping bug - the message itself uses %n to represent a line break.

**Comment by predictiple** [comment]
You're right. Sorry. In the JSON it is escaped properly. In my csv/sqlite work it was an issue but it the problem doesn't carry through to the JSON.
